src/Entity/Command.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CommandRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=CommandRepository::class)
 */
class Command
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="float")
     */
    private $totalAmount;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $civility;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPay;

    /**
     * @ORM\OneToMany(targetEntity=Contain::class, mappedBy="CommandContain")
     */
    private $contains;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commands")
     */
    private $UserOrderCommand;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    public function __construct()
    {
        $this->contains = new ArrayCollection();
        $this->created_at = new DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTotalAmount(): ?int
    {
        return $this->totalAmount;
    }

    public function setTotalAmount(int $totalAmount): self
    {
        $this->totalAmount = $totalAmount;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getCivility(): ?string
    {
        return $this->civility;
    }

    public function setCivility(string $civility): self
    {
        $this->civility = $civility;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function isPay(): ?bool
    {
        return $this->isPay;
    }

    public function setPay(bool $isPay): self
    {
        $this->isPay = $isPay;

        return $this;
    }

    /**
     * @return Collection<int, Contain>
     */
    public function getContains(): Collection
    {
        return $this->contains;
    }

    public function addContain(Contain $contain): self
    {
        if (!$this->contains->contains($contain)) {
            $this->contains[] = $contain;
            $contain->setCommandContain($this);
        }

        return $this;
    }

    public function removeContain(Contain $contain): self
    {
        if ($this->contains->removeElement($contain)) {
            // set the owning side to null (unless already changed)
            if ($contain->getCommandContain() === $this) {
                $contain->setCommandContain(null);
            }
        }

        return $this;
    }

    public function getUserOrderCommand(): ?User
    {
        return $this->UserOrderCommand;
    }

    public function setUserOrderCommand(?User $UserOrderCommand): self
    {
        $this->UserOrderCommand = $UserOrderCommand;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function __toString()
    {
        return $this->adress;
    }

}

src/Entity/Stage.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\StageRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=StageRepository::class)
 */
class Stage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=7, nullable=true)
     */
    private $backgroundColor;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbPlaceMax;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endTime;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startTime;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="stage", fetch="EAGER")
     */
    private $reservations;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->backgroundColor;
    }

    public function setBackgroundColor(?string $backgroundColor): self
    {
        $this->backgroundColor = $backgroundColor;

        return $this;
    }

    public function getNbPlaceMax(): ?int
    {
        return $this->nbPlaceMax;
    }

    public function setNbPlaceMax(int $nbPlaceMax): self
    {
        $this->nbPlaceMax = $nbPlaceMax;

        return $this;
    }


    // fonction pour afficher le nombre de place restante dans la session 
    public function getRemainingPlaces(){
        $somme = 0;
        foreach($this->reservations as $reservation)
        {
            $res = $reservation->getNbPlaces();
            $somme += $res;
        }    
        $reserved =  $this->nbPlaceMax - $somme;
            return $reserved;
        }


        // fonction pour afficher le nombre de place réserver pour la session 
        public function getNbPlaceReserved(){
        $somme = 0;
        foreach($this->reservations as $reservation)
        {
            $res= $reservation->getNbPlaces();
            $somme += $res;          
        }
        return $somme;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->endTime;
    }

    public function setEndTime(\DateTimeInterface $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setStage($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getStage() === $this) {
                $reservation->setStage(null);
            }
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
   
    /**
     * @return Int Fonction qui donne le Timstamp des variables $dateStart et $dateEnd ,Ensuite on soustrait $end a $start pour récuperer le timeStamp réel puis on calcul le nombre de jours de la formation en nombre entier
     */
    public function getAnnulation() : int
    {
        $now = new DateTime();
        $start  = $this->startTime->getTimestamp();
        $nowTimeStamp  = $now->getTimestamp();
        $days = $nowTimeStamp - $start;
        $result = (int)($days /( 60 * 60 * 24 ));
        if( $result == -1 || $result == -2){
            $date = true;
        }else{
            $date = false;
        }
        return $date;
    }
}

templates/management/addBenefit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une prestation
{% endblock %}

{% block body %}
	{{ form_start(form) }}
	{{ form_errors(form) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(form.title, { 'label': 'Titre' }) }}
			</div>
			<div class="col-4 mb-4 mt-4">
				{{ form_row(form.price, { 'label': 'Prix' }) }}
			</div>
			<div class="col-4 mb-4 mt-4">
				{{ form_row(form.img) }}
			</div>
			<div class="col-4 mb-4 mt-4">
				{{ form_row(form.backgroundColor) }}
			</div>
			<div class="col-12 mb-4 mt-4">
				{{ form_row(form.description) }}
			</div>
			<hr>
			<h2>Ajout de photos pour la gallerie d'image
			</h2>
			<div class="col-8">
				{{ form_row(form.imgCollectionBenefits) }}
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(form.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/management/addBlog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un blog
{% endblock %}

{% block body %}
	{{ form_start(formAddBlog) }}
	{{ form_errors(formAddBlog) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddBlog.title, { 'label': 'Titre' }) }}
			</div>
			<div class="col-12 mb-4 mt-4">
				{{ form_row(formAddBlog.contents) }}
			</div>
			<div class="row">
				<h3>choisisez si vous voulez poster une vidéo ou si vous voulez poster une image
				</h3>
				<div class="col-4 mb-4">
					{{ form_row(formAddBlog.image) }}
				</div>
				<div class="col-4">
					{{ form_row(formAddBlog.urlVideo, { 'label': "placer l'url de la vidéo ou le liens internet" }) }}
				</div>
				<div class="col-4">
					{{ form_row(formAddBlog.altImage, { 'label': "placer la description de l'image 100 caractères maximum" }) }}
				</div>
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddBlog.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddBlog) }}
{% endblock %}

templates/management/addCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une prestation
{% endblock %}

{% block body %}
	{{ form_start(formAddCategory) }}
	{{ form_errors(formAddCategory) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddCategory.categoryName, { 'label': 'Nom de la catégorie' }) }}
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddCategory.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddCategory) }}
{% endblock %}

templates/management/addInput.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un bénéfices à la liste
{% endblock %}

{% block body %}
	{{ form_start(formAddInput) }}
	{{ form_errors(formAddInput) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddInput.description) }}
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddInput.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddInput) }}
{% endblock %}

templates/management/addVideo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Video
{% endblock %}

{% block body %}
	{{ form_start(formAddVideo) }}
	{{ form_errors(formAddVideo) }}
	<div class="container">
		<div class="row">
			<div class="col-4 mb-4 mt-4">
				{{ form_row(formAddVideo.title, { 'label': 'Titre' }) }}
			</div>
			<div class="col-12 mb-4 mt-4">
				{{ form_row(formAddVideo.description) }}
			</div>
			<div class="row">
				<div class="col-4">
					{{ form_row(formAddVideo.alt, { 'label': "placer la description de l'image 100 caractères maximum" }) }}
				</div>
				<div class="col-4">
					{{ form_row(formAddVideo.urlVideo, { 'label': "placer l'url de la vidéo ou le liens internet" }) }}
				</div>
			</div>
			<div class="row">
				<div class="col-4 mt-4">
					{{ form_row(formAddVideo.submit, { 'label': 'Envoyer' }) }}
				</div>
			</div>
		</div>
	</div>
	{{ form_end(formAddVideo) }}
{% endblock %}

templates/management/detailBenefit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les prestation par catégorie
{% endblock %}

{% block body %}

	<div class="container">
		<div class="row">
			<h1 class="text-center">
				Ajout des bénéfices pour :
				{{ benefit }}</h1>
		</div>
		<div class="row row-cols-lg-2">
			<div class="col">
				<h2 class="mt-5 mb-5">Les bénéfice liées
				</h2>
				<table id="table_id2" class="table table-striped mt-4 display">
					<thead>
						<tr class="bg-secondary">
							<th scope="col ">Déscription</th>
							<th scope="col ">Désinscrire</th>
						</tr>
					</thead>
					<tbody>
						{% for input in benefit.inputs %}
							<tr>
								<td>{{input}}</td>
								<td>
									<button type="button" class="btn btn-lg bg-secondary mt-2 ">
										<a href="{{ path('remove_input_benefit' , {'benefit_id': benefit.id , 'input_id': input.id }) }}">Désinscrire</a>
									</button>
								{% endfor %}
							</tr>
						</tbody>
					</tbody>
				</table>
			</div>
			<div class="col">
				<h2 class="mt-5 mb-5">Les bénféfices non inscrits
				</h2>
				<table id="table_id3" class="table table-striped mt-4 display">
					<thead>
						<tr class="bg-secondary">
							<th scope="col ">Déscription</th>
							<th scope="col ">Désinscrire</th>
						</tr>
					</thead>
					<tbody>
						{% for input in noBenefits %}
							<tr>
								<td>{{input}}</td>
								<td>
									<button type="button" class="btn btn-lg bg-secondary mt-2 ">
										<a href="{{ path('add_input_benefit' , {'benefit_id': benefit.id , 'input_id': input.id }) }}">Inscrire</a>
									</button>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<button type="button" class="btn btn-lg bg-secondary mt-2 ">
				<a href="{{ path('detail_benefit', {'id': benefit.id }) }}">détail prestation</a>
			</button>
		</div>
	</div>
{% endblock %}

templates/management/detailCategory.hmtl.twig
{% extends 'base.html.twig' %}

{% block title %}Les prestation par catégorie{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <h1 class="text-center"> {{ category }}</h1>
        <button type="button" class="btn btn-lg bg-secondary mt-5  mb-5 col-3 "><a href="{{ path('add_benefit', {'id': category.id}) }}">Ajouter une prestation pour cet catégorie</a></button>
        <table id="table_id" class="table table-striped mt-4 display">
            <thead>
            <tr class="bg-secondary">
                <th scope="col ">prestation</th>
                <th scope="col">Editer</th>
                <th scope="col">supprimer</th>
            </tr>
            </thead>
            <tbody>
                {% for benefit in category.benefits %}
                <tr>
                    <td><a href="{{ path('detail_edit_benefit', {'id': benefit.id }) }}">{{ benefit }}</a></td>
                    <td><button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('edit_benefit', {'id': category.id , 'benefit_id': benefit.id }) }}">Editer</a></button></td>
                    <td>
                        <button type="button" class="btn btn-lg bg-secondary mt-2 " data-bs-toggle="modal" data-bs-target="#exampleModal{{benefit.id}}">supprimer</i></button>                 
                        <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{benefit.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Confirmer vous la supréssion de : <br>{{benefit}} ? </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                la suppression est définitif êtes vous certain de votre déscicions ? 
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-lg bg-secondary mt-2 " data-bs-dismiss="modal" > X annuler</button>
                                <button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('delete_benefit', {'id': benefit.id }) }}">supprimer</a></button>
                            </div>
                        </div>
                    </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('app_management') }}">retour</a></button>
    </div>    
</div>
{% endblock %}

templates/management/detailFacture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion du site!{% endblock %}

{% block body %}
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="card col-9 fs-4 p-4 mt-4 mb-4">
            <h2>Commande N° {{facture.id }}</h2>  
            <h3>Adresse de facturation</h3>   
            <p>{{facture.civility }} {{facture.name }}  {{facture.firstName }}, habitant à {{facture.city }} {{facture.cp }} {{facture.adress }}</p>     
            <p>Téléphone :{{facture.telephone }} / E-mail : {{facture.email }}</p>    

            <h3>Contenue facturee </h3>   
            <p>Date de la facturee : {{facture.createdAt | date('d/m/Y H:i')}}</p>        
            <p>Prix total : {{facture.totalAmount }}</p>
            <p> {% if facture.isPay %} Payement validé{% endif %}</p>

            <h3>Détails facturee </h3>  
            {% for contain in facture.contains %}
                <p><strong>Produits :</strong> {{contain.ProductContain.name}} {{contain.ProductContain.price}} € /Unités, quantités {{contain.quantity}}, total produits {{contain.ProductContain.price * contain.quantity}} € </p>
                {# <p>{{contain.ProductContain.shortDescription | raw }} </p> #}
            {% endfor %}
            <button class='btn-res btn' ><a href="{{ path('facture' , {'id': facture.id} ) }}">Exporter Facture PDF</a></button>
        </div>
    </div>    
<div>
{% endblock %}    

templates/management/facture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion du site!{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <h1 class="text-center">Liste des factures</h1>
        <table id="table_id" class="table table-striped mt-4 display">
            <thead>
            <tr class="bg-secondary">
                <th scope="col ">Id facture</th>
                <th scope="col">Date facturation</th>
                <th scope="col">Nom client</th>
                <th scope="col">Détails</th>
                <th scope="col">Télécharger PDF</th>

            </tr>
            </thead>
            <tbody>
                {% for facture in factures %}
                <tr>
                    <td class="text-center fs-5"><a  href="{{ path('detail_facture' , {"id": facture.id}) }}" >{{facture.id }}</a></td>
                    <td class="text-center fs-5">{{facture.createdAt | date('d/m/Y H:i')}}</td> 
                    <td class="text-center fs-5"><a  href="{{ path('detail_facture' , {"id": facture.id}) }}" >{{facture.name ~ facture.firstName }}</a></td>
                    <td class="text-center fs-5"><a href="{{ path('detail_facture' , {'id': facture.id}) }}">detail</a></td>
                    <td class="text-center fs-5"> <button class='btn-res btn' ><a href="{{ path('facture' , {'id': facture.id} ) }}">Exporter Facture PDF</a></button></td>                                             
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/management/showReservationSession.html.twig
{% extends 'base.html.twig' %}
{% block title %}Réservation{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <h1 class="mt-5 mb-5">Listes de toute les sessions en cours et passer </h1>            
                {# {% include "session/_showSession.html.twig" %} #}
                <table id="table_id" class="table table-striped mt-4 display">
                    <thead>
                        <tr class="bg-secondary">
                            <th scope="col ">Id</th>
                            <th scope="col">prestation</th>
                            <th scope="col">Date déroulement</th>
                            <th scope="col">Nombre de place maximum</th>               
                            <th scope="col">nombre de place réserver</th>
                            <th scope="col">nombre de place restante</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for session in sessions %}   
                        <tr>
                            <td><strong>{{ session.id }} </strong></td>
                            <td><strong>{{ session.benefit}}</strong></td>
                            <td>Le {{ session.startTime | date("d/m/Y")  }}  de {{ session.startTime | date("h:m")  }} à {{ session.endTime | date("h:m")  }}.</td>
                            <td>Place reserver : {{session.nbPlaceMax}} place(s)</td>
                            <td>Place reserver : {{session.nbPlaceReserved}} place(s)</td>
                            <td>Place restante : {{session.remainingPlaces}} place(s)</td>
                        </tr>             
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <h1 class="mt-5 mb-5">Listes de toutes les réservations</h1>            
            <table id="table_id2" class="table table-striped mt-4 display">
                <thead>
                <tr class="bg-secondary">
                    <th scope="col ">Id Session</th>
                    <th scope="col ">Nom client</th>
                    <th scope="col">Email</th>
                    <th scope="col">N°Tél</th>
                    <th scope="col">Session</th>
                    <th scope="col">date</th>
                    <th scope="col">nombre de place réserver</th>
                    <th scope="col">nombre de place restante</th>
                </tr>
                </thead>
                <tbody>
                {% for reservation in reservations %}   
                    <tr>
                        {% if reservation.session != null %}
                            <td><strong>{{ reservation.session.id }}</strong></td>
                            <td><strong>{{ reservation.name }} {{ reservation.firstName }}</strong></td>
                            {% if reservation.user.email is defined %}
                            <td><strong>{{ reservation.user.email }} </strong></td>
                            {% else %}
                            <td><strong>utilisateur supprimer </strong></td>
                            {% endif %}
                            <td><strong>{{ reservation.telephone }} </strong></td>
                            <td><strong>{{ reservation.session.benefit}}:</strong></td>
                            <td>Le {{ reservation.session.startTime | date("d/m/Y")  }}  de {{ reservation.session.startTime | date("h:m")  }} à {{ reservation.session.endTime | date("h:m")  }}.</td>
                            <td>Place reserver : {{reservation.nbPlace}} place(s)</td>
                            <td>Place restante : {{reservation.session.remainingPlaces}} place(s) /  {{reservation.session.nbPlaceMax}}</td> 
                        {% elseif reservation.stage %}
                            <td><strong>{{ reservation.stage.id }}</strong></td>
                            <td><strong>{{ reservation.name }} {{ reservation.firstName }}</strong></td>
                            {% if reservation.user.email is defined %}
                            <td><strong>{{ reservation.user.email }} </strong></td>
                            {% else %}
                            <td><strong>utilisateur supprimer </strong></td>
                            {% endif %}
                            <td><strong>{{ reservation.telephone }} </strong></td>
                            <td><strong>{{ reservation.stage.title}}:</strong></td>
                            <td>Le {{ reservation.stage.startTime | date("d/m/Y")  }}  de {{ reservation.stage.startTime | date("h:m")  }} à {{ reservation.stage.endTime | date("h:m")  }}.</td>
                            <td>Place reserver : {{reservation.nbPlace}} place(s)</td>
                            <td>Place restante : {{reservation.stage.remainingPlaces}} place(s) /  {{reservation.stage.nbPlaceMax}}</td>
                        {% endif %}
                    </tr>             
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>

{% endblock %}

templates/management/showStage.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gestion stage{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="mt-5 mb-5">Listes de tout les stages en cours et passer </h1>            
                <button type="button" class="btn btn-primary mt-5 mb-5"><a class="dropdown-item" href="{{ path('add_stage')}}">Ajouter un stage</a></button>
                <table id="table_id" class="table table-striped mt-4 display">
                    <thead>
                    <tr class="bg-secondary">
                        <th scope="col ">Id</th>
                        <th scope="col">Stage</th>
                        <th scope="col">Date déroulement</th>
                        <th scope="col">Nombre de place maximum</th>               
                        <th scope="col">nombre de place réserver</th>
                        <th scope="col">nombre de place restante</th>
                        <th scope="col ">Éditer</th>
                        <th scope="col">Supprimer</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for stage in stages %}   
                        <tr>
                            <td><strong>{{ stage.id }} </strong></td>
                            <td><strong>{{ stage.title}}</strong></td>
                            <td>Le {{ stage.startTime | date("d/m/Y h:m")  }} au {{ stage.endTime | date("d/m/Y h:m")  }}.</td>
                            <td>Place reserver : {{stage.nbPlaceMax}} place(s)</td>
                            <td>Place reserver : {{stage.nbPlaceReserved}} place(s)</td>
                            <td>Place restante : {{stage.remainingPlaces}} place(s)</td>
                            <td><a class="dropdown-item" href="{{ path('edit_stage' , {'id':stage.id }) }}">Éditer</a></td>
                            <td><a class="dropdown-item" href="{{ path('delete_stage' , {'id':stage.id }) }}">Supprimer</a></td>
                        </tr>             
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}