src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urlVideo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publication_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="videos")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $alt;

    public function __construct()
    {
        $this->publication_date = new \DateTime();

    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrlVideo(): ?string
    {
        return $this->urlVideo;
    }

    public function setUrlVideo(string $urlVideo): self
    {
        $this->urlVideo = $urlVideo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): self
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }
}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    vidéo
{% endblock %}

{% block body %}
	<section>
		<div class="header-content">
			<figure>
				<img id="header_img" src="{{asset('img/img-header.jpg')}}" alt="Yoga posture dans la montagne">
			</figure>
            <div class="header_info-blog">
				<h1 class="titre-blog">Vidéo d'<em>OM-NADA-BRAHMA</em></h1>
            </div>
		</div>
	</section>
    <div class="container mt-5">
        <div class ="row">
            <div class="row row-cols-3 row-cols-md-4 g-4">
                {% for video in videos %}
                    <div class="col">
                        <div class="card container-video-index">
                            <video controls width="100%" class="video-self" alt="{{video.alt}}">
                                <source src="/{{video.urlVideo}}" type="video/mp4">
                            </video>
                            <div class="card-body">
                                <h5 class="card-title description-title">{{video.title}}</h5>
                                <p class="card-text description-video">{{video.description | raw }}</p>
                            </div>
                        </div>
                        <div class="card-footer videomuted">
                            <small class="text-muted">{{video.user.pseudo}}</small></br>
                            <small class="text-muted">Le {{video.publicationDate | date(" l m  F Y H:m", "Europe/Paris") }}</small>
                            {% if is_granted("ROLE_ADMIN") %}
                                <p class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('edit_video',{'id': video.id , "id_user": app.user.id }) }}" class="mb-2">Editer</a></p> 
                                <p type="button" class="btn btn-lg bg-secondary mt-2 " data-bs-toggle="modal" data-bs-target="#exampleModal{{video.id}}">supprimer</i></button>                 
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal{{video.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confirmer vous la supréssion de : <br>{{video.title}} ? </h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                la suppression est définitif êtes vous certain de votre déscicions ? 
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-lg bg-secondary mt-2 " data-bs-dismiss="modal" > X annuler</button>
                                                <button type="button" class="btn btn-lg bg-secondary mt-2 "><a href="{{ path('delete_video',{'id': video.id }) }}">supprimer</a></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>    
                {% endfor %} 
            </div>
        </div>
    </div>
{% endblock %}